server {
    listen 80;
    server_name localhost, 127.0.0.1;

    set $backend_host backend;

    location /api/ {
        add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

        proxy_pass http://$backend_host:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/frontend/html;
        try_files $uri $uri/ /index.html;
    }
}
